from typing import Optional
from typing_extensions import Literal
from pydantic import BaseModel, Field
from datetime import date


# =====================================================
# ENUMS AND LITERALS
# =====================================================

PurchaseOrderStatusType = Literal[
    'DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'CANCELLED', 'COMPLETED'
]

PurchaseReceiptStatusType = Literal[
    'DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'CANCELLED', 'COMPLETED'
]


# =====================================================
# PURCHASE ORDER BASE DTOs
# =====================================================

class PurchaseOrderBase(BaseModel):
    """Base DTO for purchase order information"""
    supplier_id: str = Field(..., description="Supplier ID")
    assign_to: Optional[str] = Field(None, description="User ID of staff assigned to handle the order")
    status: Optional[PurchaseOrderStatusType] = Field(default='DRAFT', description="Purchase order status (defaults to DRAFT, auto-updated on receive)")
    order_date: date = Field(..., description="Order date")
    expected_delivery_date: Optional[date] = Field(None, description="Expected delivery date")
    notes: Optional[str] = Field(None, description="Additional notes")


# =====================================================
# PURCHASE ORDER ITEM BASE DTOs
# =====================================================

class PurchaseOrderItemBase(BaseModel):
    """Base DTO for purchase order item information"""
    product_id: str = Field(..., description="Product ID")
    qty_ordered: int = Field(..., gt=0, description="Ordered quantity")
    currency_id: str = Field(..., description="Currency ID")
    cost_price: float = Field(..., ge=0, description="Cost price")
    base_selling_price: float = Field(..., ge=0, description="Base selling price")


# =====================================================
# PURCHASE RECEIPT BASE DTOs
# =====================================================

class PurchaseReceiptItemBase(BaseModel):
    """Base DTO for purchase receipt item information"""
    purchase_order_item_id: str = Field(..., description="Purchase order item ID")
    received_qty: int = Field(..., gt=0, description="Quantity received")
    # batch_number is auto-generated by the system, not provided by users
    product_size: Optional[str] = Field(None, description="Product size")
    unit_of_measure_id: Optional[str] = Field(None, description="Unit of measure ID")
    product_expiry_date: Optional[str] = Field(None, description="Product expiry date (YYYY-MM-DD)")


class PurchaseReceiptBase(BaseModel):
    """Base DTO for purchase receipt information"""
    purchase_order_id: str = Field(..., description="Purchase order ID")
    received_date: date = Field(..., description="Date when items were received")
    description: Optional[str] = Field(None, description="Receipt description/notes")
    status: PurchaseReceiptStatusType = Field(default='DRAFT', description="Receipt status")
    items: list[PurchaseReceiptItemBase] = Field(..., description="List of received items")
